menus = {
    's': [

        {
            "id": 3,
            "name": "personal",
            "title": "个人中心",
            "path": "/personal",
            "icon": "UserOutlined",
            "permission": None,
            "component": "@/pages/personal",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 4,
            "name": "reserve",
            "title": "预约挂号",
            "path": "/reserve",
            "icon": "CalendarOutlined",
            "permission": None,
            "component": "@/pages/User_reserve.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 5,
            "name": "commentOnDoctor",
            "title": "医师评价",
            "path": "/commentOnDoctor",
            "icon": "StarOutlined",
            "permission": None,
            "component": "@/pages/User_commentOnDoctor.vue",
            "renderMenu": True,
            "parent": None,
        },

        {
            "id": 11,
            "name": "healthDocument",
            "title": "健康档案",
            "path": "/healthDocument",
            "icon": "FileTextOutlined",
            "permission": None,
            "component": "@/pages/User_healthDocument.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 12,
            "name": "reserveBodyCheck",
            "title": "体检预约",
            "path": "/reserveBodyCheck",
            "icon": "SolutionOutlined",
            "permission": None,
            "component": "@/pages/User_reserveBodyCheck.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 13,
            "name": "pay",
            "title": "在线缴费",
            "path": "/pay",
            "icon": "CreditCardOutlined",
            "permission": None,
            "component": "@/pages/User_pay.vue",
            "renderMenu": True,
            "parent": None,
        }
    ],
    't': [

        {
            "id": 3,
            "name": "personal",
            "title": "个人中心",
            "path": "/personal",
            "icon": "UserOutlined",
            "permission": None,
            "component": "@/pages/personal",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 4,
            "name": "reserve",
            "title": "预约挂号",
            "path": "/reserve",
            "icon": "CalendarOutlined",
            "permission": None,
            "component": "@/pages/User_reserve.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 5,
            "name": "commentOnDoctor",
            "title": "医师评价",
            "path": "/commentOnDoctor",
            "icon": "StarOutlined",
            "permission": None,
            "component": "@/pages/User_commentOnDoctor.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 7,
            "name": "user",
            "title": "用户管理",
            "target": "_self",
            "path": "/system/user",
            "icon": "UsergroupAddOutlined",
            "component": "@/pages/user",
            "renderMenu": True,
            "parent": "system",
            "permission": None,
            "cacheable": True,
        },
        {
            "id": 11,
            "name": "healthDocument",
            "title": "健康档案",
            "path": "/healthDocument",
            "icon": "FileTextOutlined",
            "permission": None,
            "component": "@/pages/User_healthDocument.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 13,
            "name": "pay",
            "title": "在线缴费",
            "path": "/pay",
            "icon": "CreditCardOutlined",
            "permission": None,
            "component": "@/pages/User_pay.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 31,
            "name": "family",
            "title": "家属管理",
            "path": "/family",
            "icon": "TeamOutlined",
            "permission": None,
            "component": "@/pages/Teacher_FamilyManage.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 32,
            "name": "alter",
            "title": "角色切换",
            "path": "/alter",
            "icon": "SwapOutlined",
            "permission": None,
            "component": "@/pages/Teacher_alterrole.vue",
            "renderMenu": True,
            "parent": None,
        }
    ],
    'd': [
        {
            "id": 44,
            "name": "doctor_1",
            "title": "排班查询",
            "path": "/myarrange",
            "icon": "ScheduleOutlined",  # 适合排班查询
            "permission": None,
            "component": "@/pages/Doctor_MyArrange.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 45,
            "name": "doctor_2",
            "title": "预约信息",
            "path": "/myreserved",
            "icon": "AppstoreOutlined",  # 适合预约信息
            "permission": None,
            "component": "@/pages/Doctor_Reserved.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 46,
            "name": "doctor_3",
            "title": "我的评价",
            "path": "/mycomment",
            "icon": "CommentOutlined",  # 适合医师评价
            "permission": None,
            "component": "@/pages/Doctor_comment.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 47,
            "name": "doctor_4",
            "title": "处方开具",
            "path": "/makepre",
            "icon": "FileDoneOutlined",  # 适合处方开具
            "permission": None,
            "component": "@/pages/Doctor_makePre.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 48,
            "name": "doctor_5",
            "title": "患者信息",
            "path": "/patient",
            "icon": "TeamOutlined",  # 适合患者信息
            "permission": None,
            "component": "@/pages/Doctor_patient.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 49,
            "name": "doctor_6",
            "title": "患者病历",
            "path": "/illhistory",
            "icon": "BookOutlined",  # 适合患者病历
            "permission": None,
            "component": "@/pages/Doctor_patientillhistory.vue",
            "renderMenu": True,
            "parent": None,
        }
    ],
    'a': [
        {
            "id": 14,
            "name": "admin_1",
            "title": "体检项目管理",
            "path": "/admin_bodycheck",
            "icon": "AppstoreAddOutlined",
            "permission": None,
            "component": "@/pages/Admin_BodyCheck.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 15,
            "name": "admin_2",
            "title": "体检信息管理",
            "path": "/admin_bodycheckinfo",
            "icon": "FileTextOutlined",
            "permission": None,
            "component": "@/pages/Admin_BodyCheckInfo.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 16,
            "name": "admin_3",
            "title": "医生评价管理",
            "path": "/admin_comment",
            "icon": "StarOutlined",
            "permission": None,
            "component": "@/pages/Admin_comment.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 17,
            "name": "admin_4",
            "title": "医生信息管理",
            "path": "/admin_doctor",
            "icon": "UserOutlined",
            "permission": None,
            "component": "@/pages/Admin_Doctor.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 18,
            "name": "admin_5",
            "title": "医生安排管理",
            "path": "/admin_doctorarrange",
            "icon": "CalendarOutlined",
            "permission": None,
            "component": "@/pages/Admin_DoctorArrange.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 19,
            "name": "admin_6",
            "title": "科室信息管理",
            "path": "/admin_doctorroom",
            "icon": "ApartmentOutlined",
            "permission": None,
            "component": "@/pages/Admin_DoctorRoom.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 20,
            "name": "admin_7",
            "title": "家属信息管理",
            "path": "/admin_familys",
            "icon": "TeamOutlined",
            "permission": None,
            "component": "@/pages/Admin_Familys.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 21,
            "name": "admin_8",
            "title": "诊断信息管理",
            "path": "/admin_illresult",
            "icon": "SolutionOutlined",
            "permission": None,
            "component": "@/pages/Admin_illResult.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 22,
            "name": "admin_9",
            "title": "药品信息管理",
            "path": "/admin_medicine",
            "icon": "MedicineBoxOutlined",
            "permission": None,
            "component": "@/pages/Admin_medicine.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 23,
            "name": "admin_10",
            "title": "药房信息管理",
            "path": "/admin_medicineroom",
            "icon": "ShopOutlined",
            "permission": None,
            "component": "@/pages/Admin_MedicineRoom.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 24,
            "name": "admin_11",
            "title": "药品库存管理",
            "path": "/admin_medicinestorage",
            "icon": "DatabaseOutlined",
            "permission": None,
            "component": "@/pages/Admin_medicineStorage.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 25,
            "name": "admin_12",
            "title": "图片信息管理",
            "path": "/admin_picture",
            "icon": "PictureOutlined",
            "permission": None,
            "component": "@/pages/Admin_Picture.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 26,
            "name": "admin_13",
            "title": "处方信息管理",
            "path": "/admin_prescription",
            "icon": "FileDoneOutlined",
            "permission": None,
            "component": "@/pages/Admin_Prescription.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 27,
            "name": "admin_14",
            "title": "预约记录管理",
            "path": "/admin_reserverecord",
            "icon": "BookOutlined",
            "permission": None,
            "component": "@/pages/Admin_ReserveRecord.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 28,
            "name": "admin_15",
            "title": "用户信息管理",
            "path": "/admin_users",
            "icon": "UsergroupAddOutlined",
            "permission": None,
            "component": "@/pages/Admin_Users.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 301,
            "name": "admin_17",
            "title": "管理员管理",
            "path": "/admin_admin",
            "icon": "TeamOutlined",
            "permission": None,
            "component": "@/pages/Admin_admin.vue",
            "renderMenu": True,
            "parent": None,
        },
        {
            "id": 310,
            "name": "admin_18",
            "title": "通知信息管理",
            "path": "/admin_notification",
            "icon": "NotificationOutlined",
            "permission": None,
            "component": "@/pages/Admin_notification.vue",
            "renderMenu": True,
            "parent": None,
        },
    ]
}
