# Generated by Django 5.1.2 on 2024-11-18 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointment_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("relationship", models.CharField(max_length=10)),
                ("schedule_id", models.CharField(max_length=8)),
                ("user_id", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.CharField(
                        max_length=3, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("department_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "diagnosis_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("examination", models.TextField()),
                ("examination_result", models.TextField()),
                ("reference", models.TextField()),
                ("clinical_diagnosis", models.TextField()),
                ("prescription_id", models.CharField(max_length=8)),
                ("diagnosis_time", models.DateTimeField()),
                ("id_number", models.CharField(max_length=18)),
                ("appointment_id", models.CharField(max_length=8)),
                ("doctor_id", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "drug_id",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("drug_name", models.CharField(max_length=20)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "evaluation_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("evaluation", models.TextField()),
                ("evaluation_time", models.DateTimeField()),
                ("user_id", models.CharField(max_length=8)),
                ("doctor_id", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="ExaminationArrangement",
            fields=[
                (
                    "examination_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("examination", models.TextField()),
                ("examination_date", models.DateField()),
                ("doctor_id", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="ExaminationInfo",
            fields=[
                (
                    "exam_appointment_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("examination_id", models.CharField(max_length=8)),
                ("examination_result", models.TextField(blank=True, null=True)),
                ("user_id", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "image_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("image_path", models.CharField(max_length=255)),
                (
                    "evaluation_id",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "notification_id",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("drug_id", models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("notification", models.TextField()),
                ("notification_time", models.DateTimeField()),
                ("user_id", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "pharmacy_id",
                    models.CharField(
                        max_length=2, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("pharmacy_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("diagnosis_id", models.CharField(max_length=8)),
                ("drug_id", models.CharField(max_length=9)),
                ("drug_amount", models.IntegerField()),
                ("usage", models.TextField()),
                ("precautions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "admin_id",
                    models.CharField(
                        db_index=True,
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=15)),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="admin_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="admin_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "doctor_id",
                    models.CharField(
                        db_index=True,
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=1)),
                ("title", models.CharField(max_length=10)),
                ("image_id", models.CharField(blank=True, max_length=10, null=True)),
                ("introduction", models.TextField()),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="doctor_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="doctor_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrugInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_id", models.CharField(max_length=9)),
                ("drug_amount", models.IntegerField()),
                ("pharmacy_id", models.CharField(max_length=2)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("drug_id", "pharmacy_id"), name="unique_drug_pharmacy"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=1)),
                ("birth", models.DateField()),
                ("id_number", models.CharField(max_length=18)),
                ("user_type", models.CharField(max_length=1)),
                ("phone", models.CharField(max_length=11)),
                (
                    "groups",
                    models.ManyToManyField(related_name="user_groups", to="auth.group"),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="user_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("schedule_time", models.CharField(max_length=6)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedicalSystem.department",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedicalSystem.doctor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["department_id", "doctor"],
                        name="MedicalSyst_departm_6532fa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_id", models.CharField(max_length=2)),
                ("relationship", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=1)),
                ("birth", models.DateField()),
                ("id_number", models.CharField(max_length=18)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["family_id", "user"],
                        name="MedicalSyst_family__8178f8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family_id", "user"), name="unique_family_teacher"
                    )
                ],
            },
        ),
    ]
