# Generated by Django 5.1.2 on 2024-10-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=1)),
                ("birth", models.DateField()),
                ("id_number", models.CharField(max_length=18)),
                ("user_type", models.CharField(max_length=1)),
                ("phone", models.CharField(max_length=11)),
            ],
        ),
    ]
