# Generated by Django 5.1 on 2024-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
