# Generated by Django 5.1.2 on 2024-10-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "admin_id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "staff_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=1)),
                ("title", models.CharField(max_length=10)),
                ("image_id", models.CharField(blank=True, max_length=10, null=True)),
                ("introduction", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="UserData",
            new_name="User",
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_id", models.CharField(max_length=2)),
                ("teacher_id", models.CharField(max_length=8)),
                ("relationship", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=1)),
                ("birth", models.DateField()),
                ("id_number", models.CharField(max_length=18)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family_id", "teacher_id"), name="unique_family_teacher"
                    )
                ],
            },
        ),
    ]
