# Generated by Django 5.1.2 on 2024-11-18 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examinationarrangement",
            name="doctor_id",
        ),
        migrations.RemoveField(
            model_name="examinationinfo",
            name="examination_id",
        ),
        migrations.RemoveField(
            model_name="examinationinfo",
            name="user_id",
        ),
        migrations.AddField(
            model_name="examinationarrangement",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.doctor",
            ),
        ),
        migrations.AddField(
            model_name="examinationinfo",
            name="examination_arrangement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.examinationarrangement",
            ),
        ),
        migrations.AddField(
            model_name="examinationinfo",
            name="state",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="examinationinfo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(
                db_index=True,
                max_length=3,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_time",
            field=models.DateTimeField(max_length=6),
        ),
    ]
