# Generated by Django 5.1 on 2024-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSystem', '0002_alter_image_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.CharField(max_length=50),
        ),
    ]
