# Generated by Django 5.1.2 on 2024-11-19 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0002_remove_examinationarrangement_doctor_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="schedule_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="user_id",
        ),
        migrations.AddField(
            model_name="appointment",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.schedule",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="state",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="examinationinfo",
            name="exam_appointment_id",
            field=models.CharField(
                db_index=True,
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
