# Generated by Django 5.1.2 on 2024-12-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0003_remove_appointment_schedule_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_id",
            field=models.CharField(
                db_index=True,
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="examinationarrangement",
            name="examination_id",
            field=models.CharField(
                db_index=True,
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_id", "relationship", "user"],
                name="MedicalSyst_appoint_3396e2_idx",
            ),
        ),
    ]
