# Generated by Django 5.1 on 2024-12-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSystem', '0003_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalSystem.image'),
        ),
    ]
