# Generated by Django 5.1.2 on 2024-12-04 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0004_alter_appointment_appointment_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="druginventory",
            name="unique_drug_pharmacy",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="appointment_id",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="doctor_id",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="prescription_id",
        ),
        migrations.RemoveField(
            model_name="druginventory",
            name="pharmacy_id",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="doctor_id",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="diagnosis_id",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="drug_id",
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="appointment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.appointment",
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.doctor",
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="prescription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses",
                to="MedicalSystem.prescription",
            ),
        ),
        migrations.AddField(
            model_name="druginventory",
            name="pharmacy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.doctor",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="MedicalSystem.diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="drug",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MedicalSystem.drug",
            ),
        ),
        migrations.AddIndex(
            model_name="druginventory",
            index=models.Index(
                fields=["drug_id", "pharmacy"], name="MedicalSyst_drug_id_c1a6ae_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="druginventory",
            constraint=models.UniqueConstraint(
                fields=("drug_id", "pharmacy"), name="unique_drug_pharmacy"
            ),
        ),
    ]
