# Generated by Django 5.1.2 on 2024-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0004_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="admin_id",
            field=models.CharField(
                max_length=3, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(
                max_length=3, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="diagnosis_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="staff_id",
            field=models.CharField(
                max_length=5, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="drug_id",
            field=models.CharField(
                max_length=9, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="evaluation_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="examinationarrangement",
            name="examination_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="examinationinfo",
            name="exam_appointment_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_id",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="pharmacy_id",
            field=models.CharField(
                max_length=2, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
