# Generated by Django 5.1.2 on 2024-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0005_alter_admin_admin_id_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="groups",
            field=models.ManyToManyField(related_name="admin_groups", to="auth.group"),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="admin_permissions", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="groups",
            field=models.ManyToManyField(related_name="doctor_groups", to="auth.group"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="doctor_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(related_name="user_groups", to="auth.group"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="user_permissions", to="auth.permission"
            ),
        ),
    ]
