# Generated by Django 5.1 on 2024-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSystem', '0005_alter_evaluation_evaluation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
