# Generated by Django 5.1.2 on 2024-12-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0006_evaluation_evaluation_star"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("payment_name", models.CharField(max_length=20)),
                ("payment_description", models.TextField()),
                ("money", models.FloatField()),
                ("is_paid", models.BooleanField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="MedicalSyst_appoint_3396e2_idx",
        ),
        migrations.RemoveIndex(
            model_name="schedule",
            name="MedicalSyst_departm_6532fa_idx",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="state",
            field=models.CharField(db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="familymember",
            name="id_number",
            field=models.CharField(db_index=True, max_length=18),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.CharField(db_index=True, max_length=18),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["relationship", "user"], name="MedicalSyst_relatio_a88889_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["schedule", "state"], name="MedicalSyst_schedul_febc1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["user", "state"], name="MedicalSyst_user_id_ed4780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluation",
            index=models.Index(
                fields=["doctor", "evaluation_time"],
                name="MedicalSyst_doctor__5f96e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["doctor", "department"], name="MedicalSyst_doctor__78bcee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["doctor", "schedule_time"],
                name="MedicalSyst_doctor__ed3ebc_idx",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
