# Generated by Django 5.1.2 on 2024-11-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0006_admin_groups_admin_is_active_admin_is_staff_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="is_staff",
            new_name="is_doctor",
        ),
        migrations.RenameField(
            model_name="diagnosis",
            old_name="staff_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="staff_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="is_staff",
            new_name="is_doctor",
        ),
        migrations.RenameField(
            model_name="evaluation",
            old_name="evaluated_staff_id",
            new_name="evaluated_doctor_id",
        ),
        migrations.RenameField(
            model_name="examinationarrangement",
            old_name="staff_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="staff_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_staff",
            new_name="is_doctor",
        ),
    ]
