# Generated by Django 5.1.2 on 2024-11-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0007_rename_is_staff_admin_is_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="familymember",
            name="unique_family_teacher",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="student_id",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="diagnosis",
            old_name="patient_id_number",
            new_name="id_number",
        ),
        migrations.RenameField(
            model_name="diagnosis",
            old_name="reference_range",
            new_name="reference",
        ),
        migrations.RenameField(
            model_name="evaluation",
            old_name="evaluated_doctor_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="evaluation",
            old_name="evaluation_text",
            new_name="evaluation",
        ),
        migrations.RenameField(
            model_name="evaluation",
            old_name="evaluator_student_id",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="examinationarrangement",
            old_name="examination_text",
            new_name="examination",
        ),
        migrations.RenameField(
            model_name="examinationinfo",
            old_name="student_id",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="familymember",
            old_name="teacher_id",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="notification_text",
            new_name="notification",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="recipient_student_id",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="user_id",
        ),
        migrations.AddConstraint(
            model_name="familymember",
            constraint=models.UniqueConstraint(
                fields=("family_id", "user_id"), name="unique_family_teacher"
            ),
        ),
    ]
