# Generated by Django 5.1.2 on 2024-11-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MedicalSystem", "0008_remove_familymember_unique_family_teacher_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="is_doctor",
            new_name="is_staff",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="is_doctor",
            new_name="is_staff",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_doctor",
            new_name="is_staff",
        ),
    ]
